### ISSUE TITLE
Stitch does not work at all for some projects

### ISSUE THREAD

**Issue by NyakoFox** [bscotch/stitch#83]
Pressing F5, or selecting Stitch: Run Project in the command panel both show an error, being `command 'stitch.run' not found`.

Using Visual Studio Code Insiders, if that matters.

**Comment by adam-coster** [comment]
I can't replicate this, so my best guess is that the Stitch extension either hasn't loaded yet or has run into an error, causing it to be unable to register that command.

Does the Stitch sidebar load properly (you might need to Right-click the left-most activity bar and check "Stitch" to make it visible)? My suspicion is that the extension just isn't loading at all for you.

This could be caused by a few things:

- An error when Stitch first loads (in that case a popup should appear in VSCode telling you that something went wrong with Stitch)
- The VSCode triggers that cause it to fully load the Stitch extension might not be getting triggered
  - Are you sure that there is a GameMaker project in your VSCode workspace?
  - If you open up a `.gml`, `.yy`, or `.yyp` file in the editor and *then* run the command, it should properly understand that you're in a GameMaker project

Let me know if any of those help!

**Comment by NyakoFox** [comment]
- There's no error when it first loads.
- The open folder is the base folder of the GameMaker project.
- The sidebar does NOT load properly, it's empty.
- I've tried running the command in those files and it still doesn't work.

**Comment by adam-coster** [comment]
I've since added some logging that might help to triangulate what's going on for you. If you open up the "Output" panel you should see Stitch in the dropdown. Do you see any log information indicating any errors, and/or any logs showing what the last thing was the extension tried to do?

**Comment by NyakoFox** [comment]
![image](https://github.com/bscotch/stitch/assets/87289390/82ed7965-5279-4664-b9b8-28005a0c01f8)
Here's a screenshot.

**Comment by svioletg** [comment]
I can also confirm the Stitch: Resources sidebar is empty when I open it. The output window for Stitch just gives me:

```
ERROR 03:55:17.419 [PARSER] No stitch config found, looking up runtime version
INFO 03:55:23.563 [PARSER] Loaded GML spec in 6149ms
INFO 03:55:33.862 updateFile objects/obj_player/Step_0.gml
WARN 03:55:33.863 getGmlFile: Could not find project for objects/obj_player/Step_0.gml
INFO 03:55:33.865 updateFile objects/obj_player/Step_0.gml
WARN 03:55:33.865 getGmlFile: Could not find project for objects/obj_player/Step_0.gml
INFO 03:55:33.934 updateFile objects/obj_player/Step_0.gml
WARN 03:55:33.935 getGmlFile: Could not find project for objects/obj_player/Step_0.gml
INFO 03:55:34.086 updateFile objects/obj_player/Step_0.gml
WARN 03:55:34.087 getGmlFile: Could not find project for objects/obj_player/Step_0.gml
INFO 03:55:34.143 updateFile objects/obj_player/Step_0.gml
WARN 03:55:34.144 getGmlFile: Could not find project for objects/obj_player/Step_0.gml
INFO 03:55:34.179 updateFile objects/obj_player/Step_0.gml
WARN 03:55:34.181 getGmlFile: Could not find project for objects/obj_player/Step_0.gml
INFO 03:55:35.525 updateFile objects/obj_player/Step_0.gml
WARN 03:55:35.526 getGmlFile: Could not find project for objects/obj_player/Step_0.gml
INFO 03:55:35.572 updateFile objects/obj_player/Step_0.gml
WARN 03:55:35.573 getGmlFile: Could not find project for objects/obj_player/Step_0.gml
INFO 03:55:35.621 updateFile objects/obj_player/Step_0.gml
WARN 03:55:35.621 getGmlFile: Could not find project for objects/obj_player/Step_0.gml
INFO 03:55:38.791 updateFile objects/obj_player/Step_0.gml
WARN 03:55:38.791 getGmlFile: Could not find project for objects/obj_player/Step_0.gml
INFO 03:55:38.981 updateFile objects/obj_player/Step_0.gml
WARN 03:55:38.981 getGmlFile: Could not find project for objects/obj_player/Step_0.gml
INFO 03:55:38.985 updateFile objects/obj_player/Step_0.gml
WARN 03:55:38.986 getGmlFile: Could not find project for objects/obj_player/Step_0.gml
INFO 03:55:39.764 updateFile objects/obj_player/Step_0.gml
WARN 03:55:39.765 getGmlFile: Could not find project for objects/obj_player/Step_0.gml
```

Pressing F5 or manually running "Stitch: Run Project" from the command palette results in `command stitch.run not found` regardless of whether i'm im a `.gml`, `.yy`, or `.yyp` file or not.

**Comment by adam-coster** [comment]
@svioletg @NyakoFox Thanks for this extra info! These logs appear to show that Stitch is loading, and finding your projects, but then is failing to connect what the editor sees with the files in your project.

I'll see if I can come up with some additional logging in the next update to help triangulate what's going on, but some questions that might be informative for me are:

- What version of GameMaker are you using for these projects?
- What operating system are you on (Windows/OSX/Linux), and what version?

**Comment by NyakoFox** [comment]
- I'm using GameMaker 2023.4.0.84
- Windows 11 Insiders (Canary channel), 23H2 (OS Build 25393.1)

**Comment by adam-coster** [comment]
@NyakoFox Rad, thanks! That's exactly what I'm using, so there must be something about your project that Stitch doesn't know how to handle. Based on your log output it looks like its getting stuck loading the project -- might be caught in a loop or something (there's a *lot* of recursion happening to make all of this work).

I'm adding some additional logs throughout the project loading process so we can figure out where it's getting stuck, and if we're lucky the next update will resolve this issue as a side effect since I'm working on some low level kinks with project loading.

**Comment by svioletg** [comment]
I'm running IDE v2023.4.0.84 and Runtime v2023.4.0.113, on Windows 10 21H2 (19044.2965). My VSCode workspace that I use for editing GM files is just the project folder alone loaded in as the top folder, I don't know if that would affect things at all? I'm not sure what the alternative would be, though.

**Comment by Adrian-Nelson** [comment]
I have something similar happening, my setup:
Stitch v0.29.4
VSCode 1.79.2
MacBook Pro (Ventura 13.4.1)
GameMaker IDE v2023.4.0.84 Runtime v2023.4.0.113

I have opened the root of my game repo in VSCode which is where the project file "Tomb Saver.yyp" file is, I then open the .yyp and the Stitch logs show this:
INFO 06:01:42.932 Activating extension...
INFO 06:01:42.933 Loading projects...
INFO 06:01:43.063 Loading project Tomb Saver.yyp
INFO 06:01:43.064 [PARSER] Initializing project...
INFO 06:01:43.065 [PARSER] Loading asset files...
ERROR 06:01:43.066 [PARSER] No stitch config found, looking up runtime version
INFO 06:01:43.090 [PARSER] Loaded yyp file!
ERROR 06:01:45.066 [PARSER] No spec found, using fallback
INFO 06:01:45.361 [PARSER] Loaded GML spec in 2297ms

If I edit a .gml file I see syntax highlighting but it thinks the code is Javascript/Typescript and does not like GML objects with constructors (or static functions for that matter). When I press F5 I get "command 'stitch.run' not found"

The 'STITCH: RESOURCES' pane is blank. See screenshot below showing all of these things:
<img width="1767" alt="Screenshot 2023-06-29 at 07 33 14" src="https://github.com/bscotch/stitch/assets/8666424/badbd1f0-155e-4ae6-b344-02961fb504a1">

If you need any more info please let me know - thanks.

**Comment by adam-coster** [comment]
The latest versions (>1.0.0) were published today and use a completely-overhauled parser and type system. There should also be more log information in the `Output` panel.

Did the changes resolve these issues, or generate some new logs that might explain what's going on?

**Comment by NyakoFox** [comment]
Here's the output: https://hastebin.com/share/hixabuyihe.ruby
Are there any files from my project you'd like to look at?

**Comment by adam-coster** [comment]
@NyakoFox Looks like there's something in your Rooms that Stitch doesn't know about.

If you can share any of your rooms' `.yy` files I should be able to find the problem.

I'm not sure if it's specific to one room or not, so the more room `.yy` files you can provide the better!

**Comment by NyakoFox** [comment]
[rm_testroom.zip](https://github.com/bscotch/stitch/files/12009495/rm_testroom.zip)
Here's a bunch of rooms, hope this helps

**Comment by adam-coster** [comment]
@NyakoFox That was perfect! Turns out we don't use "Tile" layers in our games so Stitch Core didn't know how to parse room files that have them.

This should be resolved in the latest version of all of the Stitch packages, including the VSCode extension.

I'll close this issue, assuming it's resolved, unless I hear otherwise!

**Comment by NyakoFox** [comment]
It seems like adding `GMRTileLayer` wasn't enough, because I'm getting errors like:

```
  {
    "code": "invalid_union_discriminator",
    "options": [
      "GMRInstanceLayer",
      "GMRBackgroundLayer",
      "GMRTileLayer"
    ],
    "path": [
      "layers",
      1,
      "resourceType"
    ],
    "message": "Invalid discriminator value. Expected 'GMRInstanceLayer' | 'GMRBackgroundLayer' | 'GMRTileLayer'"
  },
  ```

If it matters, I have asset layers as well, which doesn't seem listed in the discriminator value list!

**Comment by svioletg** [comment]
Been out of town for a week, good to see progress has been happening - latest update (v1.3.2) still doesn't seem to load the project correctly - the errors are different and more detailed now, but its still largely non-functional. What's the easiest way for me to find and post my entire output log from VSCode?

**Comment by adam-coster** [comment]
@NyakoFox WHOOPS, you were correct that I didn't have asset layers either! Those are now added to all Stitch packages, including the VSCode extension, as of a few minutes ago. Stitch VSCode v1.4.0 should now resolve all of that.

I added all of your room yy files to my test suite, so now I can guarantee that at least your rooms won't create a problem for Stitch!

@svioletg Try out v1.4.0 to see if it resolves your issues. You can attach a text file of your copy-pasted logs into a reply, or just post the logs raw in a code block, or even post a screenshot if it includes lots of visible log info. The logs from the Output > Stitch panel should contain everything that is currently being logged.

**Comment by svioletg** [comment]
Here's the log output from loading this project and attempting to hover over some symbols, and typing + erasing some misc code. I'm on v1.4.0, still can't seem to get things to be recognized unfortunately.


[2023 07 12 StitchLog.txt](https://github.com/bscotch/stitch/files/12029123/2023.07.12.StitchLog.txt)

**Comment by adam-coster** [comment]
@svioletg Looks like you have some additional room layer types that Stitch doesn't know about. If you can zip up and upload your rooms' `.yy` files I should be able to figure 5what I need to add to Stitch

**Comment by svioletg** [comment]
Can do, should be attached below.

[rooms.zip](https://github.com/bscotch/stitch/files/12029271/rooms.zip)

**Comment by adam-coster** [comment]
@svioletg Perfect, I've just published 1.4.1 that should stop erroring due to your room code!

**Comment by svioletg** [comment]
Looks like everything's settling into place! I'm noticing some misc. issues like 2D arrays seemingly not being recognized correctly:
![image](https://github.com/bscotch/stitch/assets/16344364/b667cd01-d35f-4a46-9125-3616c51553e2)

...and some color customizations not being reflected, like for built-in constants (true, false), but for the most part symbols are being recognized and the syntax highlighting is working well. Keywords like `and` or `or` don't seem to be colored at all, falling back on white, but I'm not sure whether this is just intended behavior or not - nonetheless, all of that can be addressed in their own issues (and maybe they have been, I'll need to look through them) and the core issue of it not working at all seems fixed to me.

**Comment by adam-coster** [comment]
@svioletg WHEW! Glad it's finally working!

There are some things that are technically fine in GML that we treat as legacy or as patterns we want to avoid, so Stitch just sorta ignores those.

Once GML introduced chained accessors we converted all of our 2D array accesses into chained accesses, e.g. `cell[ic,it]` became `cell[ic][it]`. We had run into a YYC compiler issues with the `[x,y]` syntax at one point and assumed that GameMaker would end up letting it decay now that `[x][y]` is preferable, so we treat it as an anti-pattern.

Since we prefer `&&` over `and` and `||` over `or`, I probably just missed including those in the syntax highlighting patterns.

I'm considering this issue to be closed for real, but you can post any new stuff as new issues. Please make separate posts for each issue though so they're easier for me to manage!
